### ISSUE TITLE
[Win] BOTW Inventory Screen Severely Garbed on Release 2.0-52+ When Not Focused

### ISSUE THREAD

**Issue by JamShady** [cemu-project/Cemu#1040]
I'm playing on W11, using a full screen window. Normally I move the mouse off-screen to hide the pointer.

From release 2.0-52 onwards, when I do this, the inventory screen is severely garbled and broken (visually, it still appears to work). The rest of the gameplay is fine, it's just limited to the inventory screen for some reason, and more particularly to the clothing items (although bows & shields do trigger it occasionally too).

![image](https://github.com/cemu-project/Cemu/assets/167395/f53138b2-5c07-4e36-a60e-b2159e92ffb7)
![image](https://github.com/cemu-project/Cemu/assets/167395/88d01f29-b398-46db-ae0a-89cfc9db868d)
![image](https://github.com/cemu-project/Cemu/assets/167395/0a666dc2-ab1f-4d62-835a-3f0f386a32eb)

**Comment by Squall-Leonhart** [comment]
That isn't unique to 2.0, and signs point to third party injection being the cause, or OOM on some graphics card / driver combos.

https://www.reddit.com/r/cemu/comments/gct0vy/botw_inventory_graphic_glitch/

**Comment by christianbittner** [comment]
used to have the same issue a handful of weeks ago. It only occurred on the armor screen for me where the icons just glitched out, causing weird flickering and red lights to appear.
I believe it was related to a graphics pack. I dont remember 100% but I know I changed a setting to fix it, maybe also look into your buffering setting, as well as if you use driver level settings like forcing the output layered on the DXGI swapchain or something like low latency mode. I just tried for 20+min to reproduce the issue but no matter which and how hard I crank the settings it wont appear anymore. 
It seems to be fixed on my end (even tried multiple res). Using a 5800X3D and a GTX 1060 6GB with the latest driver

**Comment by christianbittner** [comment]
Never mind, I got it to appear again. But only when using the double buffer option under vsync.  @JamShady turn tripple buffering on and try again. During my testing I forgot to turn it to full screen all the time before clicking on my 2nd desktop (by default CEMU fades my mouse out after~2 sec, so I dont need to tab out). I retested a bunch of configs again and the ONLY thing making the glitch appear was the double buffer solution of CEMU.

**Comment by JamShady** [comment]
@Squall-Leonhart I appreciate the insight; hard to argue with that evidence.

For me, this only started with 2.0-52. I started playing BOTW from around 2.0-29, and had over 120 hours of playtime before I ever saw this happen (upgrading as soon as releases came out). I recall this happened as soon as I'd done an upgrade recently, but didn't think too much of it at the time as I expected it'd be noted by several people and fixed in the next release. That didn't happen.

I spent an hour or so yesterday going through the recent only releases, and up to 2.0-51, everything was perfect and stable. On 2.0-52, this glitch manifests very quickly. For me at least, there is clearly something that's been introduced in 2.0-52 that's causing this to manifest, and from that I make the following observations:

- I accept that this might only occur with specific GFX card cards/combos, however that's not the ultimate root cause, because I'm using the exact same system to play without any glitches. Literally the only difference is the Cemu release. So whilst there is possibly something problematic about my combo, something in Cemu is still triggering it

- 2.0-51 played fine and showed no glitches on my recent testing to narrow down the version. It is possible that maybe I didn't give it long enough for any issue to manifest, but given my prior history of playing and never seeing this before a couple of months ago, and that it manifests very quickly on 2.0-52+ releases, I put this down to a remote possibility.



@christianbittner I did play around with the vsync settings (prior to seeing your message), and for me it also manifested on double-buffering. Triple-buffering caused horrendous screen tearing for me so I turned that off straight-away, but I will go back and check it out again. My default has been to match the emulated display up until now.

Also, I perhaps misstated things when talking about the mouse cursor; Cemu does fade the mouse out for me too, but I also click on other things off-screen (e.g. checking out cpu usage, etc) and I noticed a direct correlation between clicking off-screen and this glitch occurring. It does also occur when the Cemu is still focused with the mouse on-screen and faded, so it's not the only cause, but for me an easy way to trigger the issue.

**Comment by christianbittner** [comment]
I agree that this is annoying and hopefully can be fixed but for checking your usage you can either prepare something like task manager beforehand or use CEMUs internal tools (clicking on CEMU makes the glitch disappear immediately for me anyways).
Triple buffering should in no ways cause tearing as it is just a version of vsync and it per definition prevents tearing, unless we talk about uncapped vsync like "fast sync" on Nvidia and its AMD equivalent, should your FPS fall below refresh rate, where these methods do not wait for a blank.
speaking of vendor specific techniques: are you sure you are NOT using any driver level injected methods like from the Nvidia Control Panel for example? Like I said triple buffering is just vsync (just with a third buffer constantly getting refreshed, duh) and hearing you get tearing under triple buffer is really strange to me...
as a side note: whenever you change the style of vsync please restart CEMU, when switching between the modes I got tearing as well but thats just how it acts when changing during emulation. Sometimes even native apps can struggle with this (uncommon tho). So please re-test with frequent restarts of CEMU

**Comment by JamShady** [comment]
@christianbittner you, sir, are a genius. So the triple buffering did seem to clear the glitchy screen, and restarting Cemu resolved the screen tearing. I do seem to be dropping frames now (didn't test the fps, I can just tell by looking) and I can't work out why 'cos my card isn't maxing out or anything. I'll play around with that more, but good to know the issue has been narrowed down.

So, the question is, should this ticket be closed or not? Because it's still an issue that got introduced at a specific version; surely there should be some investigation/explanation for that?

**Comment by Squall-Leonhart** [comment]
I have never encountered this with double buffering (nvidia gpu), but i usually stick to "Experimental - Sync to Emulated display".

There was a fix for graphical issues fixed in 1.22 for double buffered vsync, i guess for some cases it has regressed.  @goeiecool9999 was the most recent to touch this code in the vulkan renderer, so maybe he has an idea.

**Comment by JamShady** [comment]
So, just for utmost clarity, in case these questions pop up later:

I played an extended session (i.e. hours) with triple buffering, no problems encountered (in terms of glitching). However, the drop in frame rates was annoying me so I switched back to 2.0-51, and again played for several hours with 'Match emulated display', and again, absolutely no problems (and no frame-rate drops).

From this perspective, I'm 100% satisfied something was added to the 2.0-52 release to introduce this problem in version 2.0.

When I was still using the latest Cemu version, I also tried to fix the v-sync via the nvidia control panel (i.e. by setting different values specifically), that didn't resolve anything either.

I'm using a GTX 1080, on Windows 11, 16Gb RAM and all updates, etc.

**Comment by Squall-Leonhart** [comment]
My theory is that the uniform buffer changes have exposed a synchronisation issue resulting in what appears to be colour bleeding, i don't know where to begin to start making changes for a possible fix.

**Comment by HobbyloserMensch** [comment]
Still an issue with the newest version but much less intense. Happened to mine when turning on fullscreen and the standard downloadable graphics enhancements. Gets worse the more mods there are installed. Got better with reinstalling everything but this is a major issue when playing this game right now.

**Comment by Squall-Leonhart** [comment]
use Triple buffering or Experimental, there hasn't been any cemu updates since this was reported.

**Comment by Exzap** [comment]
2.0-66 has a potential fix for this although I had to make an educated guess on what the cause is since I am unable replicate it on my end. Can you update and check if the problem still happens?

**Comment by christianbittner** [comment]
@Exzap I just tested it and I cannot reproduce the glitch anymore. My BOTW is fully loaded with cranked packs and I did the usual stuff of in and out of fullscreen, losing focus by clicking onto another monitor, used all vsync options (tho I dont see tearing anymore due to Gsync) while switching the menus.
I wanna note tho that I had a similar yet different issue, for me it was a red and white flickering at the left and right egde of the screen that manifested as a wide strip ending when the icons for the weapons menu started. I did not have this tilted orange surface thing as OP.
Your educated guess was spot on, at least for my issue it seems. Amazing job on that one, seriously!
If I find more time throughout the day I will test for longer periods of time than <3min for each option and see whether it creeps up again.
But since it was always so easy to trigger and I cannot for the life of me get it to show up, I'd say its pretty much fixed on my end.

**Comment by JamShady** [comment]
@Exzap thanks for this. Sorry it took me a few days to see this update. I just gave it a quick cursory check (10m) and it looks good to me. It's normally appears very quickly, so I think this is fixed. I'll close for now, and come back after a more extended playtest if something is still amiss. Good job.
