### ISSUE TITLE
Display overlay outside of game display

### ISSUE THREAD

**Issue by mariomadproductions** [cemu-project/Cemu#1588]
### Your suggestion

Feature request: (option to) display overlay outside of game display

i.e. as part of the emulator GUI, rather than overlaid on the game screen like it currently is

**Comment by SirHrVedel** [comment]
Currently the way it's implemented causes UI issues i a few games. I've only experienced that it causes UI issues in the Just Dance games, like Just Dance 2019, where it causes the whole UI to render upside down when the overlay is displayed.

So for the better it should be changed.

**Comment by Exzap** [comment]
What is "outside the game display" exactly? In a separate window? Its called "overlay" specifically because it is overlaid. Having a hard time imagining what the exact use case is here.

@SirHrVedel You should open a new issue for this. Although I am wondering if you are using a very old Cemu version, because we had a bug like that long ago that was fixed. But more details (which Cemu version you are using, what graphics card) would be helpful in general.

**Comment by mariomadproductions** [comment]
> What is "outside the game display" exactly?

I was thinking of a [status bar](https://en.wikipedia.org/wiki/Status_bar) or something like it. Doesn't have to be at the bottom though (I'd prefer it at the top tbh). Use case is: not having the game screen obscured, while still having a way to see the status updates.
